server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
#gateway:
#  routes:
#   - id: r1
#     uri: http://localhost:8081
#     predicates:
#        - Path=/customers/**
#   - id: r2
#     uri: http://localhost:8082
#     predicates:
#        - Path=/products/**
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # Ensure Eureka server runs here
#  instance:
#    preferIpAddress: true
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
#    instance-id: ${spring.application.name}:${server.port}  # Unique instance ID
#
#logging:
#  level:
#    com.netflix.discovery: DEBUG
#    com.netflix.eureka: DEBUG